export const translations = {
    en: {
        // Page d'accueil
        headline: 'No more meal planning headaches.',
        subheadline: 'Choose a criterion, we handle the rest.',
        getStarted: 'Get started!',
        footer: '© 2025 by <a href="https://kiadynirina.netlify.app/" target="_blank">KiadyN</a>. All rights reserved.',
        // FormPoppup
        customize: 'Customize your suggestion',
        gourmet: 'Gourmet suggestion',
        choose: 'Choose your preferences and let us inspire you.',
        mealType: 'Meal type:',
        mealTypePlaceholder: 'Select meal type',
        prepTime: 'Preparation time:',
        prepTimePlaceholder: 'Select max preparation time',
        prepTimeOptions: {
            under30: 'Under 30 minutes',
            under60: 'Under 60 minutes',
            under90: 'Under 90 minutes'
        },
        mood: 'Meal mood:',
        findIdeas: 'Find ideas',
        loading: 'Loading...',
        selectMealTypeError: 'Please select a meal type, mood, and preparation time.',
        noRecipeError: 'No recipes found for these criteria. Try other preferences.',
        networkError: 'Network connection issue. Check your connection and try again.',
        translationError: 'Error during retrieval or translation. Data displayed in English.',
        // Result
        suggestion: 'Here’s an idea for your',
        dishName: 'Dish name:',
        ingredients: 'Ingredients:',
        instructions: 'Instructions:',
        prepTime: 'Preparation time:',
        nutrition: 'Nutritional info:',
        anotherIdea: 'Another idea',
        modifyPrefs: 'Modify my preferences',
        minutes: 'minutes',
        recipeImageAlt: 'Recipe image',
        loadingIdea: 'Loading a new idea...',
        // Types de repas
        mealTypes: {
            breakfast: 'Breakfast',
            lunch: 'Lunch',
            dinner: 'Dinner',
            snack: 'Snack'
        },
        // Humeurs
        moods: {
            quick: 'Quick',
            vegan: 'Vegan',
            mediterranean: 'Mediterranean',
            vegetarian: 'Vegetarian',
            'high-protein': 'High-protein',
            'low-calorie': 'Low-calorie'
        },
        prepTimeWarning: 'Warning: Recipe exceeds selected preparation time of',
        prepTimeWarning2: 'but takes',
        exportPDF: 'Export to PDF',
        pdfLoadError: 'Failed to load PDF library. PDF export is unavailable.',
        pdfGenerationError: 'Failed to generate PDF. Please try again.',
        generatedOn: 'Generated on',
        footerPrefix: 'Generated by CookUp - Discover more recipes at ',
        footerUrl: 'cookuup.netlify.app',
        shareInstagram: 'Share on Instagram',
        instagramSharePrompt: 'Link copied! Paste it into your Instagram post or story.',
        copyLink: 'Copy Link',
        copySuccess: 'Copied!',
        shareFacebook: 'Share on Facebook',
        shareWhatsApp: 'Share on WhatsApp',
        copyLinkError: 'Failed to copy link.',
        exportingPDF: 'Exporting PDF...',
    },
    fr: {
        // Page d'accueil
        headline: 'Fini le casse-tête des repas.',
        subheadline: 'Choisissez un critère, on s’occupe du reste.',
        getStarted: 'C’est parti !',
        footer: '© 2025 par <a href="https://kiadynirina.netlify.app/" target="_blank">KiadyN</a>. Tous droits réservés.',
        // FormPoppup
        customize: 'Personnalisez votre suggestion',
        gourmet: 'Suggestion gourmande',
        choose: 'Choisissez vos préférences et laissez-nous vous inspirer.',
        mealType: 'Type de repas :',
        mealTypePlaceholder: 'Sélectionnez le type de repas',
        prepTime: 'Temps de préparation :',
        prepTimePlaceholder: 'Sélectionnez le temps de préparation max',
        prepTimeOptions: {
            under30: 'Moins de 30 minutes',
            under60: 'Moins de 60 minutes',
            under90: 'Moins de 90 minutes'
        },
        mood: 'Humeur du repas :',
        findIdeas: 'Trouver des idées',
        loading: 'Chargement...',
        selectMealTypeError: 'Veuillez sélectionner un type de repas, une humeur et un temps de préparation.',
        noRecipeError: 'Aucune recette trouvée pour ces critères. Essayez d’autres préférences.',
        networkError: 'Problème de connexion réseau. Vérifiez votre connexion et réessayez.',
        translationError: 'Erreur lors de la récupération ou traduction. Les données sont affichées en anglais.',
        // Result
        suggestion: 'Voici une idée pour votre',
        dishName: 'Nom du plat :',
        ingredients: 'Ingrédients :',
        instructions: 'Instructions :',
        prepTime: 'Temps de préparation :',
        nutrition: 'Infos nutritionnelles :',
        anotherIdea: 'Une autre idée',
        modifyPrefs: 'Modifier mes préférences',
        minutes: 'minutes',
        recipeImageAlt: 'Image de la recette',
        loadingIdea: 'Chargement d\'une nouvelle idée...',
        // Types de repas
        mealTypes: {
            breakfast: 'Petit-déjeuner',
            lunch: 'Déjeuner',
            dinner: 'Dîner',
            snack: 'Collation'
        },
        // Humeurs
        moods: {
            quick: 'Rapide',
            vegan: 'Végan',
            mediterranean: 'Méditerranéen',
            vegetarian: 'Végétarien',
            'high-protein': 'Protéiné',
            'low-calorie': 'Peu calorique'
        },
        prepTimeWarning: 'Attention : La recette dépasse le temps de préparation choisi de',
        prepTimeWarning2: 'mais prend',
        exportPDF: 'Exporter en PDF',
        pdfLoadError: 'Échec du chargement de la bibliothèque PDF. L\'exportation PDF est indisponible.',
        pdfGenerationError: 'Échec de la génération du PDF. Veuillez réessayer.',
        generatedOn: 'Généré le',
        footerPrefix: 'Généré par CookUp - Découvrez plus de recettes sur ',
        footerUrl: 'cookuup.netlify.app',
        shareInstagram: 'Partager sur Instagram',
        instagramSharePrompt: 'Lien copié ! Collez-le dans votre publication ou story Instagram.',
        copyLink: 'Copier le lien',
        copySuccess: 'Copié !',
        shareFacebook: 'Partager sur Facebook',
        shareWhatsApp: 'Partager sur WhatsApp',
        copyLinkError: 'Échec de la copie du lien.',
        exportingPDF: 'Exportation du PDF...'
    }
};